articles/urls.py
from django.urls import path
from . import views #현재 폴더와 같은 위치에서 가져옴 그래서 . 사용

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update')
]

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles':articles,
    }
    return render(request, 'index.html', context)

def detail(request, id):
    article = Article.objects.get(id=id)

    context = {
        'article': article,
    }

    return render(request, 'detail.html', context)

def new(request):
    return render(request, 'new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article()
    article.title = title
    article.content = content
    article.save()

    return redirect('articles:detail', id=article.id)


def delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()

    return redirect('articles:index')

def edit(request, id):
    article = Article.objects.get(id=id)

    context = {
        'article': article,
    }

    return render(request, 'edit.html', context)

def update(request, id):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article.objects.get(id=id)
    article.title = title
    article.content = content
    article.save()

    return redirect('articles:detail', id=article.id)

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}
<div class="card">
    <div class="card-header">
        {{article.title}}
    </div>
    <div class="card-body">
        {{article.content}}
    </div>
    <div class="card-footer">
        {{article.created_at}}
    </div>
</div>
<a href="{% url 'articles:delete' id=article.id %}" class="btn btn-danger">delete</a>
<a href="{% url 'articles:edit' id=article.id %}" class="btn btn-warning">update</a>
{% endblock %}

articles/templates/edit.html
{% extends 'base.html' %}

{% block body %}
<form action="{% url 'articles:update' id=article.id %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" id="title" class="form-control" name="title" value="{{article.title}}">
    </div>
    <div class="mb-3">
        <label for="content" class="form-label">content</label>
        <textarea id="content" class="form-control" rows="10" name="content">{{article.content}}</textarea>
    </div>

    <button type="submit" class="btn btn-primary">submit</button>
</form>
{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}


{% block body %}
    <table class="table">
        <thead>
            <tr>
                <th>title</th>
                <th>created_at</th>
                <th>link</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
                <tr>
                    <td>{{article.title}}</td>
                    <td>{{article.created_at}}</td>
                    <td><a href="{% url 'articles:detail' id=article.id %}">link</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{%  endblock %}

articles/templates/new.html
{% extends 'base.html' %}

{% block body %}
<form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" id="title" class="form-control" name="title">
    </div>
    <div class="mb-3">
        <label for="content" class="form-label">content</label>
        <textarea id="content" class="form-control" rows="10" name="content"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">submit</button>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="nav">
        <a class="nav-link" href="{% url 'articles:index' %}">Home</a>
        <a class="nav-link" href="{% url 'articles:new' %}">Create</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
    </nav>

    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>